### ISSUE TITLE
Confused about the 'regress_ranges' in fcos_reid_head.py

### ISSUE THREAD

**Issue by Ning5195** [daodaofr/AlignPS#12]
Thank you for your nice work!
I'm confused about the 'regress_ranges' in fcos_reid_head.py. It is set as ((-1, INF), (-2, -1), (-2, -1), (-2, -1), (-2, -1)). In other words, although the output contains {P3, P4, P5, P6, P6, P7}, the others have no effect except P3? Is it the same as 'regress_ranges =  ((-1, INF),)'? Are there any other settings related to the design of learning features only from P3?
I really can't figure this out. Thanks for your answers!

**Comment by daodaofr** [comment]
This implementation just set all the gt bounding box to P3, the output from other layers are considered as backgrounds. Another way is to remove the outputs from other layers, by removing some output layers in FPN, I think the results will be similar.

**Comment by FeboReigns** [comment]
CUKH-SYSU Recall  AP  mAP   top-1
P3                  90.3  81.2  93.1   93.4
P4                  87.5 78.7  92.7    93.1
P5                   79.0 71.7  89.3   89.5
P3, P4              90.4 80.5 91.1   91.6
P3, P4, P5        90.9 80.4 90.0   90.5

I would like to confirm the experimental situation of these data. If you use P3 and P4, I know that P3 and P4 are positive samples at the time of training, and the other layers are background. However, when testing, the output of the FPN is P3 and P4, or only one P3?
我想确认一下，这几个数据的实验情况。如果使用P3和P4，我知道训练时P3和P4 是正样本，其他层是背景。但是测试时FPN的输出是P3和P4，还是只有P3一个?

I also tried, and the output of the FPN at training was only P3, which dropped by 2% on the PRW dataset. I think the reason this is possible is because it's like GLCNet said,background knowledge helps prospective learning. Thank you for providing the baseline, my master's thesis was intended to improve AlignPS.
另外我做了尝试，在训练时FPN的输出也只用P3，在PRW数据集上下降了2%。我认为之所以会这样可能时因为正像GLCNet
中说的，背景知识帮助了前景学习。
